import { Button } from 'antd'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { createAuthUser } from '../services/authService'
import styles from '../styles/Home.module.css'
import {IUser} from '../utils/types'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Notex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Button type='primary'>Test2</Button>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

// export async function getServerSideProps() {
//   const newUser: IUser = {name: "Test", email: "test.user@abc.com", surname: "User"};
//   await createAuthUser(newUser, "123456");
//   // Pass data to the page via props
//   return {props: {}}
// }

export default Home
